### ISSUE TITLE
Failed to load a language-hclrs package grammar

### ISSUE THREAD

**Issue by tmatijevich** [50Wliu/language-hclrs#2]
I'm unable to install tree-sitter grammars on Windows

1. Clone or install language-hclrs
2. Launch Atom

**Atom**: 1.56.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [language-hclrs](https://github.com/50Wliu/language-hclrs) package 0.0.1

### Stack Trace

Failed to load a language-hclrs package grammar

```
At Cannot find module 'tree-sitter-hclrs'
Require stack:
- C:\Users\b\.atom\packages\language-hclrs\grammars\hclrs.cson in C:\Users\b\.atom\packages\language-hclrs\grammars\hclrs.cson

Error: Cannot find module 'tree-sitter-hclrs'
Require stack:
- C:\Users\b\.atom\packages\language-hclrs\grammars\hclrs.cson
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:157820)
    at new TreeSitterGrammar (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:3408385)
    at GrammarRegistry.createGrammar (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:362405)
    at ~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:362246
    at ~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:11:584869
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
  at /packages/language-hclrs/grammars/hclrs.cson:1:1
```

### Commands

```
```

### Non-Core Packages

```
Delete-Whitelines 0.6.4 
highlight-selected 0.17.0 
language-as-structured-text 0.2.2 
language-batchfile 0.7.5 
language-hclrs 0.0.1 
language-ignore 1.8.0 
language-matlab 0.2.1 
language-matlab-octave 1.0.5 
minimap 4.39.10 
minimap-find-and-replace 5.0.8 
minimap-highlight-selected 4.6.5 
multi-cursor 3.0.0 
sort-lines 0.19.0 
split-diff 1.6.1 
tabs-to-spaces 1.0.5 
zentabs 0.8.9 
```

**Comment by winstliu** [comment]
How did you install language-hclrs? Looks like it didn't install its dependency package (tree-sitter-hclrs), which is odd.

**Comment by tmatijevich** [comment]
Above, I cloned to `%userprofile%\.atom\packages` and re-launched Atom

Additionally, now I attempted the install from Settings/Install... after installing [cert-tweaks](https://github.com/nikitakit/cert-tweaks) and launching with [this env var](https://github.com/atom/apm/issues/340#issuecomment-438212048)

![image](https://user-images.githubusercontent.com/33841634/123999839-8edc7100-d998-11eb-8c56-076d5fb77d5a.png)

Here's the log
[2021-06-30T16_40_45_620Z-debug.log](https://github.com/50Wliu/language-hclrs/files/6742608/2021-06-30T16_40_45_620Z-debug.log)

**Comment by winstliu** [comment]
Could you try:
1. Deleting language-hclrs from ~/.atom/packages
2. Installing it from the Settings UI, or through `apm install language-hclrs`

Does it work then?

**Comment by tmatijevich** [comment]
Hello,
I apologize for the confusion. I anticipated you would ask that.
The [comment above](https://github.com/50Wliu/language-hclrs/issues/2#issuecomment-871566460) is the installation result for Settings UI with attached log and image.

**Comment by winstliu** [comment]
Yes, sorry...I think what I meant to ask was "did you delete the cloned repo from .atom/packages before trying to install through the UI"? If yes, you might want to create an issue in atom/atom or atom/apm instead -- it looks like apm can't find node, which would affect more package installations than just this one.

**Comment by tmatijevich** [comment]
Got it.
Yes, I cleared it from `.atom/packages`. Then re-attempted.
Yes I already created an [issue on atom/atom](https://github.com/atom/atom/issues/22675) suspecting it may involve more tree-sitter grammars.

It's probably more suited for apm.
Core packages seem to work find with tree-sitter (toggling the core setting "User Tree Sitter Parsers"), but I can't find why manually installed community packages with tree-sitter fails on windows.

I think you can close it here if I'm seeing the same problem elsewhere.
Thanks for answering

**Comment by winstliu** [comment]
> Core packages seem to work find with tree-sitter (toggling the core setting "User Tree Sitter Parsers"), but I can't find why manually installed community packages with tree-sitter fails on windows.

This is probably because those already have all their dependencies installed for them and are included as a part of the installer.

I'll close this because it seems to be a broader issue with your installation.
