### ISSUE TITLE
No syntax highlighting in macOS big sur

### ISSUE THREAD

**Issue by dw61** [50Wliu/language-hclrs#4]
As discussed in #3, the syntax highlighting of hclrs doesn't show up in my atom editor. I put my cursor at the comment at line 16, and it seemed that `source.hclrs` scope is used.

<img width="1440" alt="Screen Shot 2021-09-27 at 13 12 06" src="https://user-images.githubusercontent.com/27620726/134955653-275fcee9-044f-4e29-a0e6-7c276e5866a9.png">

**Comment by winstliu** [comment]
Thanks! And while I get everything on my end set up, can you confirm that the "Use Tree Sitter Parsers" setting is enabled? (`core.useTreeSitterParsers`)

**Comment by dw61** [comment]
Yes! I think it's enabled

<img width="818" alt="Screen Shot 2021-09-27 at 20 19 13" src="https://user-images.githubusercontent.com/27620726/135002505-e97a158a-2941-4d5f-bba7-fad46a0638e0.png">

**Comment by winstliu** [comment]
Okay, I can reproduce it on my end. Perhaps bumping tree-sitter 5 versions at once without checking for breaking changes was a bad idea. I'll take a look through the documentation and see if I can figure out why it's not working :D.

**Comment by winstliu** [comment]
![Incompatible tree-sitter version](https://user-images.githubusercontent.com/2766036/135005646-79cd10b2-0d84-432b-bba1-f45fa35e1bc9.png)
Well then. I'll downgrade tree-sitter and have a new version out shortly.

**Comment by winstliu** [comment]
Okay, Atom is giving me a heck of a bad time so I can't test my own changes (it keeps redirecting my Python installation to a non-existent directory so I can't update the package...).

Can you please try upgrading again? Hopefully it works this time 🤞.

I've also reported the underlying bug to the Atom repo.

**Comment by winstliu** [comment]
![Working syntax highlighting](https://user-images.githubusercontent.com/2766036/135014627-2e222198-e330-49ec-b8ab-d22fdedae2d0.png)
Hah! It works!

Please let me know while using it if there's anything else you would like to see highlighted :). Sorry for all the hassle in getting this working!

(Also, for future self, delete `$env:ATOM_HOME\.node-gyp\AppData` for things to start installing again.)

**Comment by dw61** [comment]
Great! It worked for me too! Hope I could have an easier time in my lab this Wednesday lol
